#!/usr/bin/env python3
# Bake Spektrafilm film stocks into 3D LUT atlases for the SafeLight extension.
#
# This is an OFFLINE build tool. It is the ONLY place the GPLv3 Spektrafilm
# engine is touched: it runs the spectral simulation on a grid of input colours
# and writes the result as data (base64 rgba8 atlases) into
# src/stocks.generated.ts. SafeLight itself never links the engine — it only
# loads the baked LUT bytes. The generated LUT data derives from Spektrafilm's
# CC BY-SA 4.0 profiles, so keep the attribution in the README.
#
# Requirements:
#   - A working Spektrafilm install (https://github.com/andreavolpato/spektrafilm)
#     and its film/print datasheet data.
#   - numpy.
#
# The shaper window and atlas layout MUST match src/lut.ts. Edit both together.

import base64
import math
import sys

import numpy as np

# ── Must match src/lut.ts ────────────────────────────────────────────────────
LUT_SIZE = 33
SHAPER_MIN_EV = -10.0
SHAPER_MAX_EV = 6.0
ATLAS_W = LUT_SIZE * LUT_SIZE
ATLAS_H = LUT_SIZE

# Which stocks to bake: (id, display name, spektrafilm negative, print paper).
# Fill these in from the stocks your Spektrafilm install ships.
STOCKS = [
    # ("portra400", "Kodak Portra 400", "kodak_portra_400", "kodak_endura"),
    # ("vision3_250d", "Kodak Vision3 250D", "kodak_vision3_250d", "kodak_2383"),
]


def unshape(s: np.ndarray) -> np.ndarray:
    """Shaped coord [0,1] -> scene-linear (inverse of the GLSL shaper)."""
    return np.power(2.0, s * (SHAPER_MAX_EV - SHAPER_MIN_EV) + SHAPER_MIN_EV)


def lin_to_srgb(x: np.ndarray) -> np.ndarray:
    x = np.clip(x, 0.0, 1.0)
    return np.where(x <= 0.0031308, x * 12.92, 1.055 * np.power(x, 1 / 2.4) - 0.055)


def grid_inputs() -> np.ndarray:
    """The N^3 scene-linear input colours, in atlas order (r fastest, then g, then b)."""
    n = LUT_SIZE
    axis = np.linspace(0.0, 1.0, n)
    lin_axis = unshape(axis)
    # atlas pixel (x,y): x = b*n + r, y = g  -> iterate b, g, r
    out = np.zeros((n * n * n, 3), dtype=np.float64)
    i = 0
    for b in range(n):
        for g in range(n):
            for r in range(n):
                out[i] = (lin_axis[r], lin_axis[g], lin_axis[b])
                i += 1
    return out


def render_with_spektrafilm(inputs: np.ndarray, negative: str, paper: str) -> np.ndarray:
    """Run Spektrafilm on scene-linear RGB inputs, return display sRGB-linear RGB.

    WIRE THIS TO YOUR SPEKTRAFILM INSTALL. The engine reconstructs a spectrum per
    input colour, exposes the negative emulsion, develops dye densities, prints
    through the enlarger onto `paper`, and scans the print. Return per-pixel
    *linear* (not yet sRGB-encoded) display RGB in [0,1]; lin_to_srgb is applied
    below for 8-bit storage.

    The exact import depends on the Spektrafilm version — adapt as needed, e.g.:

        from spektrafilm import Pipeline
        pipe = Pipeline(negative=negative, print_paper=paper)
        return pipe.process_linear(inputs)   # (M,3) linear display RGB
    """
    raise NotImplementedError(
        "Wire render_with_spektrafilm() to your Spektrafilm install "
        f"(negative={negative!r}, paper={paper!r})."
    )


def atlas_bytes(srgb: np.ndarray) -> bytes:
    """Pack (M,3) sRGB [0,1] into an rgba8 atlas (ATLAS_W*ATLAS_H*4), opaque."""
    rgb8 = np.clip(np.round(srgb * 255.0), 0, 255).astype(np.uint8)
    rgba = np.empty((rgb8.shape[0], 4), dtype=np.uint8)
    rgba[:, :3] = rgb8
    rgba[:, 3] = 255
    return rgba.reshape(-1).tobytes()


def main() -> int:
    if not STOCKS:
        print("No stocks configured. Edit STOCKS in tools/bake_luts.py.", file=sys.stderr)
        return 1

    inputs = grid_inputs()
    entries = []
    for sid, name, negative, paper in STOCKS:
        print(f"baking {sid} ({name})…", file=sys.stderr)
        linear = render_with_spektrafilm(inputs, negative, paper)
        srgb = lin_to_srgb(np.asarray(linear, dtype=np.float64))
        b64 = base64.b64encode(atlas_bytes(srgb)).decode("ascii")
        entries.append((sid, name, b64))

    lines = [
        "// AUTO-GENERATED by tools/bake_luts.py — do not edit by hand.",
        "// LUT data derived from Spektrafilm profiles (CC BY-SA 4.0).",
        "",
        'import type { Stock } from "./lut";',
        'import { decodeBase64Atlas } from "./lut";',
        "",
        "export const BAKED_STOCKS: Stock[] = [",
    ]
    for sid, name, b64 in entries:
        lines.append(f'  {{ id: {sid!r}, name: {name!r}, atlas: () => decodeBase64Atlas({b64!r}) }},')
    lines.append("];")
    out = "\n".join(lines) + "\n"

    with open("src/stocks.generated.ts", "w", encoding="utf-8") as f:
        f.write(out)
    print(f"wrote src/stocks.generated.ts ({len(entries)} stock(s))", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
