#!/usr/bin/env node
// Convert spektrafilm-lut .cube files into src/stocks.generated.ts.
//
// Run AFTER baking with Spektrafilm's CLI. Each .cube must be 33^3 and baked
// with sRGB input + output, so it lines up with the extension's shader:
//
//   spektrafilm-lut build --film kodak_portra_400 --print kodak_portra_endura \
//     --input srgb --output srgb --resolution 33 --out ./baked
//   node tools/cube_to_stocks.mjs ./baked
//   npm run build
//
// Usage:
//   node tools/cube_to_stocks.mjs <path> [<path> ...]
// where each <path> is a .cube file or a directory scanned recursively for
// *.cube (a "combinations" subdir is skipped). Each cube becomes one stock:
//   id   = file basename (without .cube)   name = id, "_" -> " ", Title Cased
// Rename the .cube files first if you want friendlier ids/names.

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, basename, extname } from "node:path";

const N = 33;
const ATLAS_W = N * N;
const ATLAS_H = N;

function collectCubes(paths) {
  const out = [];
  for (const p of paths) {
    if (statSync(p).isDirectory()) {
      for (const e of readdirSync(p)) {
        if (e === "combinations") continue;
        const full = join(p, e);
        if (statSync(full).isDirectory()) out.push(...collectCubes([full]));
        else if (extname(e).toLowerCase() === ".cube") out.push(full);
      }
    } else if (extname(p).toLowerCase() === ".cube") {
      out.push(p);
    }
  }
  return out;
}

function parseCube(text) {
  let size = 0;
  const data = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    if (line.startsWith("LUT_3D_SIZE")) {
      size = parseInt(line.split(/\s+/)[1], 10);
      continue;
    }
    if (/^[A-Za-z_]/.test(line)) continue; // TITLE, DOMAIN_MIN/MAX, etc.
    const parts = line.split(/\s+/).map(Number);
    if (parts.length >= 3 && parts.slice(0, 3).every(Number.isFinite)) {
      data.push([parts[0], parts[1], parts[2]]);
    }
  }
  return { size, data };
}

function atlasFromCube(cube, file) {
  if (cube.size !== N) {
    throw new Error(`${file}: LUT_3D_SIZE ${cube.size}, expected ${N} (bake with --resolution ${N})`);
  }
  if (cube.data.length !== N * N * N) {
    throw new Error(`${file}: ${cube.data.length} entries, expected ${N ** 3}`);
  }
  const atlas = new Uint8Array(ATLAS_W * ATLAS_H * 4);
  // .cube order: red varies fastest → index k = r + g*N + b*N*N.
  for (let k = 0; k < cube.data.length; k++) {
    const r = k % N;
    const g = Math.floor(k / N) % N;
    const b = Math.floor(k / (N * N));
    const idx = (g * ATLAS_W + (b * N + r)) * 4;
    const c = cube.data[k];
    atlas[idx] = clamp8(c[0]);
    atlas[idx + 1] = clamp8(c[1]);
    atlas[idx + 2] = clamp8(c[2]);
    atlas[idx + 3] = 255;
  }
  return atlas;
}

const clamp8 = (v) => Math.max(0, Math.min(255, Math.round(v * 255)));
const prettyName = (id) =>
  id
    .replace(/[_-]+/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase())
    // Uppercase a stock-letter that trails a number (400h → 400H, 250d → 250D).
    .replace(/(\d)([a-z])/g, (_, d, l) => d + l.toUpperCase());

const args = process.argv.slice(2);
if (args.length === 0) {
  console.error("usage: node tools/cube_to_stocks.mjs <cube-or-dir> [...]");
  process.exit(1);
}
const cubes = collectCubes(args);
if (cubes.length === 0) {
  console.error("no .cube files found");
  process.exit(1);
}

const entries = [];
for (const file of cubes) {
  const id = basename(file, extname(file));
  const atlas = atlasFromCube(parseCube(readFileSync(file, "utf8")), file);
  entries.push({ id, name: prettyName(id), b64: Buffer.from(atlas).toString("base64") });
  console.error(`baked ${id} (${atlas.length} bytes)`);
}

const out = [
  "// AUTO-GENERATED by tools/cube_to_stocks.mjs — do not edit by hand.",
  "// LUT data derived from Spektrafilm profiles (CC BY-SA 4.0).",
  "",
  'import type { Stock } from "./lut";',
  'import { decodeBase64Atlas } from "./lut";',
  "",
  "export const BAKED_STOCKS: Stock[] = [",
  ...entries.map(
    (e) =>
      `  { id: ${JSON.stringify(e.id)}, name: ${JSON.stringify(e.name)}, atlas: () => decodeBase64Atlas(${JSON.stringify(e.b64)}) },`,
  ),
  "];",
  "",
].join("\n");

writeFileSync("src/stocks.generated.ts", out);
console.error(`wrote src/stocks.generated.ts (${entries.length} stock(s))`);
