// AUTO-GENERATED by tools/cube_to_stocks.mjs — do not edit by hand.
//
// Empty by default: the extension ships with only the neutral placeholder LUT.
// Bake real stocks with Spektrafilm's `spektrafilm-lut` CLI, then run
// `node tools/cube_to_stocks.mjs <dir>` to regenerate this file. See README.

import type { Stock } from "./lut";
// import { decodeBase64Atlas } from "./lut";

export const BAKED_STOCKS: Stock[] = [];
