// AUTO-GENERATED by tools/bake_luts.py — do not edit by hand.
//
// Empty by default: the extension ships with only the neutral placeholder LUT.
// Run the bake tool against the Spektrafilm engine + film datasheets to fill
// this with real stocks (each entry decodes a base64 rgba8 atlas on demand).

import type { Stock } from "./lut";
// import { decodeBase64Atlas } from "./lut";

export const BAKED_STOCKS: Stock[] = [];
